// End-to-end confidential-transfer check (token-2022 v11.0.0 + zk-sdk 6.0.1).
//
// Exercises the full token-2022 ConfidentialTransfer extension flow against
// a target network and asserts that:
//   1. The auditor can decrypt the on-chain transfer ciphertext to the
//      cleartext amount (validates the ZK ElGamal Proof program at runtime).
//   2. Public balances are consistent post-deposit / post-withdraw.
//
// Migration note (2026-05-13): this test was rewritten off `spl-token-client`
// because that crate hard-pins `spl-token-2022 = ^10.0.0`. All orchestration
// (mint/account create, configure, deposit, transfer, withdraw, context-state
// accounts, record-account chunked writes) is hand-rolled in `token_ops.rs`
// using `spl-token-2022 = 11.0.0` builders directly. Proofs are generated by
// upstream `spl-token-confidential-transfer-proof-generation = 0.6.0` (which
// is internally pinned to `solana-zk-sdk = 6.0.1`).
//
// Localnet: skipped — litesvm bundles a `spl-token-2022` build *without* the
// `zk-ops` feature, so confidential ops return `InvalidInstructionData`
// regardless of proof contents. Run against devnet/testnet/mainnet.

use anyhow::{Context, Result};
use async_trait::async_trait;
use log::info;

use solana_client::{
    nonblocking::rpc_client::RpcClient as NonblockingRpcClient,
    rpc_client::RpcClient as BlockingRpcClient,
    rpc_config::{CommitmentConfig, RpcTransactionConfig},
};
use solana_keypair::Keypair;
use solana_pubkey::Pubkey;
use solana_signature::Signature;
use solana_signer::Signer;
use std::sync::Arc;

use solana_transaction_status_client_types::{
    EncodedTransaction, UiMessage, UiTransactionEncoding,
};

use solana_zk_elgamal_proof_interface::{
    instruction::ProofInstruction, proof_data::batched_range_proof::BatchedRangeProofContext,
};
use solana_zk_sdk::encryption::{
    auth_encryption::{AeCiphertext, AeKey},
    elgamal::{ElGamalCiphertext, ElGamalKeypair, ElGamalPubkey},
};
use solana_zk_sdk_pod::encryption::elgamal::PodElGamalPubkey;
use spl_token_2022_interface::extension::confidential_transfer::{
    instruction::TransferInstructionData, ConfidentialTransferAccount,
};
use spl_token_confidential_transfer_proof_generation::{
    transfer::transfer_split_proof_data, try_combine_lo_hi_ciphertexts,
    withdraw::withdraw_proof_data, TRANSFER_AMOUNT_LO_BITS,
};

use super::token_ops;
use test_common::{E2eContext, E2eTest, LabeledTransactionSignature, TestOutcome};

const MINT_DECIMALS: u8 = 2;
const MINT_AMOUNT: u64 = 100_00; // 100.00 tokens
const DEPOSIT_AMOUNT: u64 = 50_00;
const TRANSFER_AMOUNT: u64 = 50_00;
const WITHDRAW_AMOUNT: u64 = 20_00;

pub struct ConfidentialTransfersE2e;

#[async_trait(?Send)]
impl E2eTest for ConfidentialTransfersE2e {
    fn id(&self) -> &'static str {
        "e2e_confidential_transfers"
    }

    async fn run(&self, ctx: E2eContext) -> Result<TestOutcome> {
        // Localnet skip: litesvm bundles a `spl-token-2022` program built
        // WITHOUT the `zk-ops` feature flag, so Deposit / Withdraw /
        // Transfer all return `InvalidInstructionData` regardless of
        // proof validity. The flow only works against a real validator
        // (devnet/testnet/mainnet) whose token-2022 program enables
        // zk-ops. Skip cleanly to keep local runs green.
        if ctx.network_name == "localnet" {
            return Ok(TestOutcome::Skip {
                reason: "localnet litesvm bundles spl-token-2022 without the `zk-ops` \
                         feature; confidential ops always fail with InvalidInstructionData. \
                         Run against devnet/testnet/mainnet."
                    .to_string(),
            });
        }

        let mut sigs: Vec<LabeledTransactionSignature> = Vec::new();
        match run_inner(&ctx, &mut sigs).await {
            Ok(message) => Ok(TestOutcome::Pass {
                message,
                tx_signatures: sigs,
            }),
            Err(e) => Ok(TestOutcome::Fail {
                message: format!("confidential transfers failed: {e:#}"),
                tx_signatures: sigs,
            }),
        }
    }
}

async fn run_inner(
    ctx: &E2eContext,
    sigs: &mut Vec<LabeledTransactionSignature>,
) -> Result<String> {
    info!(
        "confidential_transfers: starting against network={} rpc={}",
        ctx.network_name, ctx.rpc_url
    );

    // Required program: token-2022.
    let expected_token_program = spl_token_2022_interface::id();
    let token_program_id = ctx
        .required_programs
        .first()
        .copied()
        .context("missing required token-2022 program in e2e context")?;
    if token_program_id != expected_token_program {
        anyhow::bail!(
            "required program {} does not match spl_token_2022::id() {}",
            token_program_id,
            expected_token_program
        );
    }

    let rpc = Arc::new(NonblockingRpcClient::new_with_commitment(
        ctx.rpc_url.clone(),
        CommitmentConfig::confirmed(),
    ));

    let payer = ctx.payer.insecure_clone();
    let mint = Keypair::new();
    let mint_authority = Keypair::new();
    let sender_owner = Keypair::new();
    let recipient_owner = Keypair::new();
    let auditor = ElGamalKeypair::new_rand();

    info!(
        "confidential_transfers: keypairs generated (mint={}, sender_owner={}, recipient_owner={})",
        mint.pubkey(),
        sender_owner.pubkey(),
        recipient_owner.pubkey()
    );

    // ---- 1. Create mint with ConfidentialTransferMint extension ----
    info!("confidential_transfers: step 1/11 — creating mint with ConfidentialTransferMint extension...");
    let auditor_pod: PodElGamalPubkey = (*auditor.pubkey()).into();
    let sig = token_ops::create_confidential_mint(
        &rpc,
        &payer,
        &mint,
        &mint_authority.pubkey(),
        MINT_DECIMALS,
        Some(auditor_pod),
    )
    .await
    .context("create_mint")?;
    sigs.push(label_sig("create-mint", sig));
    info!(
        "confidential_transfers: step 1/11 done — mint {} created",
        mint.pubkey()
    );

    // ---- 2. Sender confidential account ----
    info!(
        "confidential_transfers: step 2/11 — creating + configuring sender confidential account..."
    );
    let sender_token_account_kp = Keypair::new();
    let sender_token_account = sender_token_account_kp.pubkey();
    let sig = token_ops::create_confidential_token_account(
        &rpc,
        &payer,
        &sender_token_account_kp,
        &sender_owner.pubkey(),
        &mint.pubkey(),
    )
    .await
    .context("create sender token account")?;
    sigs.push(label_sig("sender-account-create", sig));

    let sender_elgamal =
        ElGamalKeypair::new_from_signer(&sender_owner, &sender_token_account.to_bytes())
            .map_err(|e| anyhow::anyhow!("sender elgamal derive: {e}"))?;
    let sender_aes = AeKey::new_from_signer(&sender_owner, &sender_token_account.to_bytes())
        .map_err(|e| anyhow::anyhow!("sender aes derive: {e}"))?;

    let sig = token_ops::configure_account(
        &rpc,
        &payer,
        &sender_owner,
        &sender_token_account,
        &mint.pubkey(),
        &sender_elgamal,
        &sender_aes,
    )
    .await
    .with_context(|| {
        format!(
            "configure sender account (sender_elgamal_pubkey={})",
            sender_elgamal.pubkey()
        )
    })?;
    sigs.push(label_sig("sender-account-configure", sig));
    info!(
        "confidential_transfers: step 2/11 done — sender account {} configured",
        sender_token_account
    );

    // ---- 3. Recipient confidential account ----
    info!("confidential_transfers: step 3/11 — creating + configuring recipient confidential account...");
    let recipient_token_account_kp = Keypair::new();
    let recipient_token_account = recipient_token_account_kp.pubkey();
    let sig = token_ops::create_confidential_token_account(
        &rpc,
        &payer,
        &recipient_token_account_kp,
        &recipient_owner.pubkey(),
        &mint.pubkey(),
    )
    .await
    .context("create recipient token account")?;
    sigs.push(label_sig("recipient-account-create", sig));

    let recipient_elgamal =
        ElGamalKeypair::new_from_signer(&recipient_owner, &recipient_token_account.to_bytes())
            .map_err(|e| anyhow::anyhow!("recipient elgamal derive: {e}"))?;
    let recipient_aes =
        AeKey::new_from_signer(&recipient_owner, &recipient_token_account.to_bytes())
            .map_err(|e| anyhow::anyhow!("recipient aes derive: {e}"))?;

    let sig = token_ops::configure_account(
        &rpc,
        &payer,
        &recipient_owner,
        &recipient_token_account,
        &mint.pubkey(),
        &recipient_elgamal,
        &recipient_aes,
    )
    .await
    .context("configure recipient account")?;
    sigs.push(label_sig("recipient-account-configure", sig));
    info!(
        "confidential_transfers: step 3/11 done — recipient account {} configured",
        recipient_token_account
    );

    // ---- 4. Mint public tokens to sender ----
    info!(
        "confidential_transfers: step 4/11 — minting {} public tokens to sender...",
        MINT_AMOUNT
    );
    let sig = token_ops::mint_to(
        &rpc,
        &payer,
        &mint.pubkey(),
        &sender_token_account,
        &mint_authority,
        MINT_AMOUNT,
    )
    .await
    .context("mint_to sender")?;
    sigs.push(label_sig("mint-to-sender", sig));
    info!(
        "confidential_transfers: step 4/11 done — minted {} to sender",
        MINT_AMOUNT
    );

    // ---- 5. Deposit half to confidential balance ----
    info!(
        "confidential_transfers: step 5/11 — depositing {} from public to confidential balance...",
        DEPOSIT_AMOUNT
    );
    let sig = token_ops::confidential_deposit(
        &rpc,
        &payer,
        &sender_owner,
        &sender_token_account,
        &mint.pubkey(),
        DEPOSIT_AMOUNT,
        MINT_DECIMALS,
    )
    .await
    .context("deposit to confidential balance")?;
    sigs.push(label_sig("sender-deposit", sig));
    info!(
        "confidential_transfers: step 5/11 done — deposited {}",
        DEPOSIT_AMOUNT
    );

    // ---- 6. Apply pending balance (sender) ----
    info!("confidential_transfers: step 6/11 — applying sender pending balance...");
    let sender_state = token_ops::get_token_account_state(&rpc, &sender_token_account)
        .await
        .context("fetch sender account before apply_pending")?;
    let ct_acc = token_ops::confidential_transfer_extension(&sender_state)?;
    let pending_credit_counter: u64 = ct_acc.pending_balance_credit_counter.into();
    // After apply, the available balance equals DEPOSIT_AMOUNT.
    let new_decryptable_sender = sender_aes.encrypt(DEPOSIT_AMOUNT).into();
    let sig = token_ops::apply_pending_balance(
        &rpc,
        &payer,
        &sender_owner,
        &sender_token_account,
        pending_credit_counter,
        &new_decryptable_sender,
    )
    .await
    .context("apply pending balance (sender)")?;
    sigs.push(label_sig("sender-apply-pending", sig));
    info!("confidential_transfers: step 6/11 done — sender pending balance applied");

    // ---- 7. Confidential transfer (split proofs via context-state accounts) ----
    info!(
        "confidential_transfers: step 7/11 — running confidential transfer of {} sender→recipient...",
        TRANSFER_AMOUNT
    );
    let transfer_sig = run_confidential_transfer(
        &rpc,
        &payer,
        &sender_owner,
        &sender_token_account,
        &recipient_token_account,
        &mint.pubkey(),
        &sender_elgamal,
        &sender_aes,
        recipient_elgamal.pubkey(),
        auditor.pubkey(),
        TRANSFER_AMOUNT,
        sigs,
    )
    .await
    .context("confidential transfer")?;
    info!(
        "confidential_transfers: step 7/11 done — transfer tx {} confirmed",
        transfer_sig
    );

    // ---- 8. Apply pending balance (recipient) ----
    info!("confidential_transfers: step 8/11 — applying recipient pending balance...");
    let recipient_state = token_ops::get_token_account_state(&rpc, &recipient_token_account)
        .await
        .context("fetch recipient account before apply_pending")?;
    let r_ct_acc = token_ops::confidential_transfer_extension(&recipient_state)?;
    let r_pending_counter: u64 = r_ct_acc.pending_balance_credit_counter.into();
    let new_decryptable_recipient = recipient_aes.encrypt(TRANSFER_AMOUNT).into();
    let sig = token_ops::apply_pending_balance(
        &rpc,
        &payer,
        &recipient_owner,
        &recipient_token_account,
        r_pending_counter,
        &new_decryptable_recipient,
    )
    .await
    .context("apply pending balance (recipient)")?;
    sigs.push(label_sig("recipient-apply-pending", sig));
    info!("confidential_transfers: step 8/11 done — recipient pending balance applied");

    // ---- 9. Withdraw to recipient public balance ----
    info!(
        "confidential_transfers: step 9/11 — running confidential withdraw of {} to recipient public balance...",
        WITHDRAW_AMOUNT
    );
    run_confidential_withdraw(
        &rpc,
        &payer,
        &recipient_owner,
        &recipient_token_account,
        &mint.pubkey(),
        &recipient_elgamal,
        &recipient_aes,
        TRANSFER_AMOUNT,
        WITHDRAW_AMOUNT,
        sigs,
    )
    .await
    .context("withdraw from recipient confidential balance")?;
    info!(
        "confidential_transfers: step 9/11 done — withdraw of {} settled",
        WITHDRAW_AMOUNT
    );

    // ---- 10. Auditor decrypt assertion ----
    info!(
        "confidential_transfers: step 10/11 — auditor decrypting on-chain transfer ciphertext..."
    );
    let decrypted = auditor_decrypt_transfer_amount(&ctx.rpc_client, &transfer_sig, &auditor)
        .context("auditor decrypt")?;
    if decrypted != TRANSFER_AMOUNT {
        anyhow::bail!(
            "auditor decrypted amount mismatch: expected {}, got {}",
            TRANSFER_AMOUNT,
            decrypted
        );
    }
    info!(
        "confidential_transfers: step 10/11 done — auditor decrypted transfer amount = {} (matches expected)",
        decrypted
    );

    // ---- 11. Balance assertions ----
    info!("confidential_transfers: step 11/11 — verifying post-flow public balances...");
    let sender_final = token_ops::get_token_account_state(&rpc, &sender_token_account)
        .await
        .context("fetch sender account state (final)")?;
    let recipient_final = token_ops::get_token_account_state(&rpc, &recipient_token_account)
        .await
        .context("fetch recipient account state (final)")?;
    let expected_sender_public = MINT_AMOUNT - DEPOSIT_AMOUNT;
    let expected_recipient_public = WITHDRAW_AMOUNT;
    let sender_amount: u64 = sender_final.base.amount.into();
    let recipient_amount: u64 = recipient_final.base.amount.into();
    if sender_amount != expected_sender_public {
        anyhow::bail!(
            "sender public balance mismatch: expected {}, got {}",
            expected_sender_public,
            sender_amount
        );
    }
    if recipient_amount != expected_recipient_public {
        anyhow::bail!(
            "recipient public balance mismatch: expected {}, got {}",
            expected_recipient_public,
            recipient_amount
        );
    }
    info!(
        "confidential_transfers: step 11/11 done — sender public={}, recipient public={}",
        sender_amount, recipient_amount
    );

    Ok(format!(
        "confidential transfer end-to-end verified: auditor decrypted {}, sender public {}, recipient public {}",
        decrypted, sender_amount, recipient_amount
    ))
}

/// Wrap a raw `Signature` as a `LabeledTransactionSignature` with success=true.
fn label_sig(name: &str, sig: Signature) -> LabeledTransactionSignature {
    LabeledTransactionSignature {
        label: name.to_string(),
        signature: sig.to_string(),
        success: true,
        error: None,
    }
}

/// Fetch the transfer transaction, locate the `Transfer` instruction, and
/// decrypt the auditor ciphertext into a cleartext `u64` amount.
fn auditor_decrypt_transfer_amount(
    rpc: &BlockingRpcClient,
    sig: &Signature,
    auditor: &ElGamalKeypair,
) -> Result<u64> {
    let config = RpcTransactionConfig {
        encoding: Some(UiTransactionEncoding::Json),
        commitment: Some(CommitmentConfig::confirmed()),
        max_supported_transaction_version: Some(0),
    };
    let tx = rpc
        .get_transaction_with_config(sig, config)
        .context("fetch transfer transaction")?;
    let EncodedTransaction::Json(ui_tx) = tx.transaction.transaction else {
        anyhow::bail!("unexpected transaction encoding");
    };
    let UiMessage::Raw(raw) = ui_tx.message else {
        anyhow::bail!("unexpected message encoding");
    };
    for ix in &raw.instructions {
        let Ok(input) = bs58::decode(&ix.data).into_vec() else {
            continue;
        };
        if input.is_empty() {
            continue;
        }
        if input.len() < 2 {
            continue;
        }
        // ConfidentialTransfer Transfer ix: byte 0 = ConfidentialTransferExtension
        // discriminator (token-2022 outer), byte 1 = ConfidentialTransferInstruction::Transfer.
        // TransferInstructionData follows starting at byte 2.
        const TRANSFER_DATA_LEN: usize = core::mem::size_of::<TransferInstructionData>();
        if input.len() < 2 + TRANSFER_DATA_LEN {
            continue;
        }
        if let Ok(decoded) =
            bytemuck::try_from_bytes::<TransferInstructionData>(&input[2..2 + TRANSFER_DATA_LEN])
        {
            let ct_lo: ElGamalCiphertext = decoded
                .transfer_amount_auditor_ciphertext_lo
                .try_into()
                .map_err(|e| anyhow::anyhow!("decode auditor ciphertext lo: {e:?}"))?;
            let ct_hi: ElGamalCiphertext = decoded
                .transfer_amount_auditor_ciphertext_hi
                .try_into()
                .map_err(|e| anyhow::anyhow!("decode auditor ciphertext hi: {e:?}"))?;
            let combined = try_combine_lo_hi_ciphertexts(&ct_lo, &ct_hi, TRANSFER_AMOUNT_LO_BITS)
                .ok_or_else(|| anyhow::anyhow!("failed to combine ciphertexts"))?;
            let decrypted = auditor.secret().decrypt(&combined);
            let amount = decrypted
                .decode_u32()
                .ok_or_else(|| anyhow::anyhow!("failed to decode u32"))?;
            return Ok(amount as u64);
        }
    }
    anyhow::bail!("no TransferInstructionData found in transfer transaction");
}

pub fn register() -> Box<dyn E2eTest> {
    Box::new(ConfidentialTransfersE2e)
}

// ---------------------------------------------------------------------------
// Confidential transfer flow (split proofs via context-state + record accounts)
// ---------------------------------------------------------------------------

#[allow(clippy::too_many_arguments)]
async fn run_confidential_transfer(
    rpc: &NonblockingRpcClient,
    payer: &Keypair,
    source_owner: &Keypair,
    source_token_account: &Pubkey,
    destination_token_account: &Pubkey,
    _mint: &Pubkey,
    source_elgamal: &ElGamalKeypair,
    source_aes: &AeKey,
    destination_elgamal_pubkey: &ElGamalPubkey,
    auditor_elgamal_pubkey: &ElGamalPubkey,
    transfer_amount: u64,
    sigs: &mut Vec<LabeledTransactionSignature>,
) -> Result<Signature> {
    use spl_token_2022_interface::extension::confidential_transfer::instruction as ct_ix;

    // 1. Fetch source account state.
    info!("confidential_transfers/transfer: fetching source account state...");
    let state = token_ops::get_token_account_state(rpc, source_token_account)
        .await
        .context("fetch source account info")?;
    let ct_acc: &ConfidentialTransferAccount = token_ops::confidential_transfer_extension(&state)?;

    // Decode current available ciphertext + AE-decrypt current decryptable balance.
    let current_available_ct: ElGamalCiphertext = ct_acc
        .available_balance
        .try_into()
        .map_err(|e| anyhow::anyhow!("decode current available balance: {e:?}"))?;
    let current_decryptable_ae: AeCiphertext = ct_acc
        .decryptable_available_balance
        .try_into()
        .map_err(|e| anyhow::anyhow!("decode current decryptable balance: {e:?}"))?;
    let current_balance = current_decryptable_ae
        .decrypt(source_aes)
        .ok_or_else(|| anyhow::anyhow!("decrypt current decryptable available balance"))?;

    // 2. Generate the three transfer proofs (upstream v6).
    info!("confidential_transfers/transfer: generating proofs (equality + ciphertext-validity + range U128)...");
    let proofs = transfer_split_proof_data(
        &current_available_ct,
        &current_decryptable_ae,
        transfer_amount,
        source_elgamal,
        source_aes,
        destination_elgamal_pubkey,
        Some(auditor_elgamal_pubkey),
    )
    .map_err(|e| anyhow::anyhow!("transfer_split_proof_data: {e:?}"))?;
    info!("confidential_transfers/transfer: proofs generated");

    // 3. Create context-state accounts for equality + validity proofs
    //    (each small enough to fit in one tx).
    let proof_authority = Keypair::new();
    let equality_kp = Keypair::new();
    let validity_kp = Keypair::new();
    let range_kp = Keypair::new();

    let sig = token_ops::create_context_state_account(
        rpc,
        payer,
        &equality_kp,
        &proof_authority.pubkey(),
        &proofs.equality_proof_data,
        ProofInstruction::VerifyCiphertextCommitmentEquality,
    )
    .await
    .context("create equality context-state account")?;
    sigs.push(label_sig("transfer-ctx-equality-create", sig));
    info!(
        "confidential_transfers/transfer: equality ctx-state created ({})",
        equality_kp.pubkey()
    );

    let sig = token_ops::create_context_state_account(
        rpc,
        payer,
        &validity_kp,
        &proof_authority.pubkey(),
        &proofs
            .ciphertext_validity_proof_data_with_ciphertext
            .proof_data,
        ProofInstruction::VerifyBatchedGroupedCiphertext3HandlesValidity,
    )
    .await
    .context("create ciphertext-validity context-state account")?;
    sigs.push(label_sig("transfer-ctx-validity-create", sig));
    info!(
        "confidential_transfers/transfer: validity ctx-state created ({})",
        validity_kp.pubkey()
    );

    // 4. Range proof (U128 ≈ 1.4 KB) — write to spl_record account, then
    //    verify_proof_from_account into a context-state account.
    let range_record_kp = Keypair::new();
    info!(
        "confidential_transfers/transfer: writing range U128 proof to record account {} (chunked)...",
        range_record_kp.pubkey()
    );
    let range_proof_bytes = bytemuck::bytes_of(&proofs.range_proof_data);
    let record_results = token_ops::create_record_account(
        rpc,
        payer,
        &range_record_kp,
        &proof_authority,
        range_proof_bytes,
    )
    .await
    .context("create range record account")?;
    for (label, sig) in &record_results {
        sigs.push(label_sig(&format!("transfer-range-{label}"), *sig));
    }
    info!("confidential_transfers/transfer: range proof written to record account");

    let sig = token_ops::create_context_state_account_from_record::<BatchedRangeProofContext>(
        rpc,
        payer,
        &range_kp,
        &proof_authority.pubkey(),
        &range_record_kp.pubkey(),
        spl_record::state::RecordData::WRITABLE_START_INDEX as u32,
        ProofInstruction::VerifyBatchedRangeProofU128,
    )
    .await
    .context("create range context-state account from record")?;
    sigs.push(label_sig("transfer-ctx-range-create", sig));
    info!(
        "confidential_transfers/transfer: range ctx-state created ({})",
        range_kp.pubkey()
    );

    // 5. Compute new decryptable available balance + submit the Transfer ix.
    let new_available_balance = current_balance
        .checked_sub(transfer_amount)
        .ok_or_else(|| anyhow::anyhow!("transfer_amount exceeds current available balance"))?;
    let new_decryptable = source_aes.encrypt(new_available_balance).into();

    info!("confidential_transfers/transfer: submitting Transfer instruction (3 ctx-state account refs)...");
    use spl_token_confidential_transfer_proof_extraction::instruction::ProofLocation;
    let equality_location = ProofLocation::ContextStateAccount(&equality_kp.pubkey());
    let validity_location = ProofLocation::ContextStateAccount(&validity_kp.pubkey());
    let range_location = ProofLocation::ContextStateAccount(&range_kp.pubkey());

    let transfer_ixs = ct_ix::transfer(
        &spl_token_2022_interface::id(),
        source_token_account,
        _mint,
        destination_token_account,
        &new_decryptable,
        &proofs
            .ciphertext_validity_proof_data_with_ciphertext
            .ciphertext_lo,
        &proofs
            .ciphertext_validity_proof_data_with_ciphertext
            .ciphertext_hi,
        &source_owner.pubkey(),
        &[],
        equality_location,
        validity_location,
        range_location,
    )
    .map_err(|e| anyhow::anyhow!("build transfer ix: {e:?}"))?;
    let transfer_sig = token_ops::send_ixs(rpc, payer, &[source_owner], &transfer_ixs)
        .await
        .context("submit Transfer instruction")?;
    sigs.push(label_sig("confidential-transfer", transfer_sig));
    info!(
        "confidential_transfers/transfer: Transfer tx submitted: {}",
        transfer_sig
    );

    // 6. Close ctx-state and record accounts, reclaiming rent.
    info!(
        "confidential_transfers/transfer: closing 3 ctx-state accounts + range record account..."
    );
    for (label_name, ctx_kp) in [
        ("transfer-ctx-equality-close", &equality_kp),
        ("transfer-ctx-validity-close", &validity_kp),
        ("transfer-ctx-range-close", &range_kp),
    ] {
        let sig = token_ops::close_context_state_account(
            rpc,
            payer,
            &proof_authority,
            &ctx_kp.pubkey(),
            &payer.pubkey(),
        )
        .await
        .with_context(|| format!("close context-state account {}", ctx_kp.pubkey()))?;
        sigs.push(label_sig(label_name, sig));
    }
    let sig = token_ops::close_record_account(
        rpc,
        payer,
        &proof_authority,
        &range_record_kp.pubkey(),
        &payer.pubkey(),
    )
    .await
    .context("close range record account")?;
    sigs.push(label_sig("transfer-range-record-close", sig));
    info!("confidential_transfers/transfer: rent reclaimed");

    Ok(transfer_sig)
}

#[allow(clippy::too_many_arguments)]
async fn run_confidential_withdraw(
    rpc: &NonblockingRpcClient,
    payer: &Keypair,
    owner: &Keypair,
    token_account: &Pubkey,
    mint: &Pubkey,
    elgamal: &ElGamalKeypair,
    aes: &AeKey,
    current_balance: u64,
    withdraw_amount: u64,
    sigs: &mut Vec<LabeledTransactionSignature>,
) -> Result<()> {
    use spl_token_2022_interface::extension::confidential_transfer::instruction as ct_ix;

    info!("confidential_transfers/withdraw: fetching source account state...");
    let state = token_ops::get_token_account_state(rpc, token_account)
        .await
        .context("fetch withdraw source account info")?;
    let ct_acc = token_ops::confidential_transfer_extension(&state)?;
    let current_available_ct: ElGamalCiphertext = ct_acc
        .available_balance
        .try_into()
        .map_err(|e| anyhow::anyhow!("decode current available balance: {e:?}"))?;

    info!("confidential_transfers/withdraw: generating proofs (equality + range U64)...");
    let proofs = withdraw_proof_data(
        &current_available_ct,
        current_balance,
        withdraw_amount,
        elgamal,
    )
    .map_err(|e| anyhow::anyhow!("withdraw_proof_data: {e:?}"))?;
    info!("confidential_transfers/withdraw: proofs generated");

    let proof_authority = Keypair::new();
    let equality_kp = Keypair::new();
    let range_kp = Keypair::new();

    let sig = token_ops::create_context_state_account(
        rpc,
        payer,
        &equality_kp,
        &proof_authority.pubkey(),
        &proofs.equality_proof_data,
        ProofInstruction::VerifyCiphertextCommitmentEquality,
    )
    .await
    .context("create withdraw equality context-state account")?;
    sigs.push(label_sig("withdraw-ctx-equality-create", sig));
    info!(
        "confidential_transfers/withdraw: equality ctx-state created ({})",
        equality_kp.pubkey()
    );

    // Range proof (U64) — same record-account pattern the transfer flow uses
    // for its U128 range proof. `BatchedRangeProofU64Data` is
    // BatchedRangeProofContext (~264 B) + PodRangeProofU64 (672 B) ≈ 936 B
    // inline, which combined with `create_account` + a second signer + tx
    // overhead exceeds the 1232-byte raw VersionedTransaction limit. Routing
    // through `spl_record` + `verify_proof_from_account` keeps every on-the-
    // wire tx well under that cap.
    let range_record_kp = Keypair::new();
    info!(
        "confidential_transfers/withdraw: writing range U64 proof to record account {} (chunked)...",
        range_record_kp.pubkey()
    );
    let range_proof_bytes = bytemuck::bytes_of(&proofs.range_proof_data);
    let record_results = token_ops::create_record_account(
        rpc,
        payer,
        &range_record_kp,
        &proof_authority,
        range_proof_bytes,
    )
    .await
    .context("create withdraw range record account")?;
    for (label, sig) in &record_results {
        sigs.push(label_sig(&format!("withdraw-range-{label}"), *sig));
    }
    info!("confidential_transfers/withdraw: range proof written to record account");

    let sig = token_ops::create_context_state_account_from_record::<BatchedRangeProofContext>(
        rpc,
        payer,
        &range_kp,
        &proof_authority.pubkey(),
        &range_record_kp.pubkey(),
        spl_record::state::RecordData::WRITABLE_START_INDEX as u32,
        ProofInstruction::VerifyBatchedRangeProofU64,
    )
    .await
    .context("create withdraw range context-state account from record")?;
    sigs.push(label_sig("withdraw-ctx-range-create", sig));
    info!(
        "confidential_transfers/withdraw: range ctx-state created ({})",
        range_kp.pubkey()
    );

    let new_balance = current_balance - withdraw_amount;
    let new_decryptable = aes.encrypt(new_balance).into();
    use spl_token_confidential_transfer_proof_extraction::instruction::ProofLocation;
    let equality_location = ProofLocation::ContextStateAccount(&equality_kp.pubkey());
    let range_location = ProofLocation::ContextStateAccount(&range_kp.pubkey());

    let withdraw_ixs = ct_ix::withdraw(
        &spl_token_2022_interface::id(),
        token_account,
        mint,
        withdraw_amount,
        MINT_DECIMALS,
        &new_decryptable,
        &owner.pubkey(),
        &[],
        equality_location,
        range_location,
    )
    .map_err(|e| anyhow::anyhow!("build withdraw ixs: {e:?}"))?;
    let withdraw_sig = token_ops::send_ixs(rpc, payer, &[owner], &withdraw_ixs)
        .await
        .context("submit Withdraw instruction")?;
    sigs.push(label_sig("recipient-withdraw", withdraw_sig));
    info!(
        "confidential_transfers/withdraw: Withdraw tx submitted: {}; closing ctx-state accounts + record account...",
        withdraw_sig
    );

    for (label_name, ctx_kp) in [
        ("withdraw-ctx-equality-close", &equality_kp),
        ("withdraw-ctx-range-close", &range_kp),
    ] {
        let sig = token_ops::close_context_state_account(
            rpc,
            payer,
            &proof_authority,
            &ctx_kp.pubkey(),
            &payer.pubkey(),
        )
        .await
        .with_context(|| format!("close withdraw context-state account {}", ctx_kp.pubkey()))?;
        sigs.push(label_sig(label_name, sig));
    }
    let sig = token_ops::close_record_account(
        rpc,
        payer,
        &proof_authority,
        &range_record_kp.pubkey(),
        &payer.pubkey(),
    )
    .await
    .context("close withdraw range record account")?;
    sigs.push(label_sig("withdraw-range-record-close", sig));
    info!("confidential_transfers/withdraw: rent reclaimed");

    Ok(())
}
